//! A NATS core client in Rust, usable with no weida in the picture.
//!
//! This crate is a **product, not an adapter**: it implements the client half
//! of the NATS client protocol for applications that speak NATS, rather than
//! bridging NATS into weida
//! ([0013](../../../docs/decisions/0013-competitor-libraries.md) §4, §4.5).
//!
//! What it shares with weida is the machine room: `weida-runtime`'s reactor,
//! resolver and close budget, and `weida-core`'s error vocabulary at the
//! boundary. `[dependencies]` names `weida-runtime`, `weida-core` and
//! `weida-nats-codec`, and **never** `weida` or `weida-protocol` [0013 §4.2].
//!
//! # Client, not server
//!
//! Routes, gateways, leaf nodes and JetStream are server features
//! ([0014](../../../docs/decisions/0014-parallel-libraries.md) §2), so this
//! crate is Core NATS as a client sees it: `INFO`/`CONNECT`, `PING`/`PONG`,
//! publish, subscribe with queue groups, and request-reply over an inbox. A
//! queue group is not a broker queue — it is a set of subscriptions sharing
//! one eligible delivery per publication — and that is a client-side concept
//! the protocol defines for a client, so it belongs here.
//!
//! # Shape
//!
//! * [`Connection`] — the handshake and the driver that owns the wire: the
//!   server's `INFO` read first, `CONNECT` answered with one credential
//!   form, TLS where `INFO` demands it, the pings in both directions with the
//!   unanswered ones bounded, and asynchronous `INFO` handled outside the
//!   handshake.
//! * [`Subscription`] — one `SUB`, its client-chosen `sid`, its optional
//!   queue group, and `UNSUB` with or without a message count.
//! * [`subject`] — the two wildcards as a pure function, and what is not a
//!   subject at all.
//! * [`Message`] — subject, `sid`, reply subject, headers and opaque
//!   payload, owned.
//! * [`options`] — every `CONNECT` field, every credential form, and every
//!   bound, each one marked the protocol's own or ours.
//! * [`transport`] — the byte stream, the one way TLS gets under it, and the
//!   operation reader.
//! * [`request`] — the inbox, the mandatory window, and the difference
//!   between no responder and no answer.
//! * [`Error`] — why something failed, in the protocol's own words where it
//!   has any.
//!
//! ```no_run
//! use std::time::Duration;
//! use weida_nats::{Connection, options::ConnectionOptions};
//! use weida_runtime::Exec;
//!
//! # async fn example() -> Result<(), weida_nats::Error> {
//! let exec = Exec::current()?;
//! let nats = Connection::connect(&exec, "127.0.0.1", 4222, ConnectionOptions::new()).await?;
//!
//! let mut orders = nats.subscribe("orders.>").await?;
//! nats.publish("orders.created", b"{}").await?;
//!
//! // The window is mandatory: a request API that can hang is a bug.
//! let reply = nats.request("service.echo", b"ping", Duration::from_secs(2)).await?;
//! assert_eq!(reply.payload, b"ping");
//!
//! while let Some(message) = orders.next().await {
//!     println!("{:?} {:?}", message.subject_str(), message.payload);
//!     break;
//! }
//! nats.close().await?;
//! # Ok(())
//! # }
//! ```
//!
//! # Bounds
//!
//! Every table whose size a peer can influence has a named bound, and
//! [`options`] states for each one whether the bound is the protocol's or
//! ours. The protocol's own are `INFO.max_payload`, `max_control_line`,
//! `max_pending` and `max_pings_out`; the client's own are the subscription
//! table, the inbox map of pending requests, the retained `connect_urls`, the
//! header-entry count and the per-subscription message queue — because the
//! protocol bounds none of those, and in the case of the subscription table
//! it *cannot*: the `sid` is "generated by the client", so nothing but the
//! client is in a position to stop the table from growing.
//!
//! # Where this client departs from the text
//!
//! * **NKey and JWT signing is the caller's, and there is no cryptographic
//!   dependency.** "A server that gives a nonce expects the NKey client to
//!   sign that nonce in `CONNECT`" (`docs/research/nats.md` §1), and an NKey
//!   signature is Ed25519 over that nonce with the user's seed. This crate
//!   models that as [`options::Signer`]: a closure the caller supplies, which
//!   receives the nonce **unchanged** and returns the signature and — for the
//!   NKey form — the public key. The key material is the application's, for
//!   exactly the reason the `rustls::ClientConfig` is the application's, and a
//!   messaging library that held a private key and chose an algorithm would be
//!   making the application's security decision for it. The evidence that
//!   nothing is lost: `CONNECT.sig` and `CONNECT.nkey` are strings the
//!   reference defines as base64url, so a caller that can sign can fill them,
//!   and `tests/handshake.rs` pins that the nonce arrives byte for byte and
//!   that the answer lands in `sig`.
//! * **The `CONNECT` is confirmed with a `PING`.** The reference gives no
//!   acknowledgement for `CONNECT`: with `verbose: false` a server that
//!   accepted it says nothing and a server that refused it sends `-ERR` and
//!   closes. Writing `CONNECT` and `PING` together and waiting for the `PONG`
//!   makes the handshake end in an answer either way. Every mainstream client
//!   does this; the reference does not say to.
//! * **The inbox token is unique and not secret.** `_INBOX.` plus "something
//!   unique" is the whole requirement. This crate builds the token from the
//!   process id, a nanosecond clock reading and a process-local counter — not
//!   from a cryptographic random source, because it has none and will not grow
//!   one. An inbox name is a routing token rather than a secret: authorization
//!   is the server's (§12 P14, subject permissions per account), so guessing
//!   the subject buys an attacker exactly what a subject permission already
//!   allows it. What correctness needs is that two requests never share a
//!   reply subject, and the counter gives that within a process, the process
//!   id across processes, and the clock across restarts that reuse one. An
//!   application that needs an unguessable inbox sets
//!   [`options::ConnectionOptions::inbox_prefix`] from a source it trusts.
//! * **The degenerate subjects are refused, not normalised.** The reference
//!   gives the grammar as dot-separated tokens and stops. So `""`, `.a`, `a.`
//!   and `a..b` are all refused by one rule — no token may be empty — because
//!   `a..b` and `a.b` are *different* subjects to a server that accepted them
//!   and collapsing the dot would publish somewhere the caller did not name.
//!   `nats-server` answers `-ERR 'Invalid Subject'` for these, so refusing
//!   locally reports the same fact one round trip earlier. The full table is
//!   in [`subject`].
//! * **A wildcard is a whole token or it is literal text.** `orders.*x` has a
//!   literal second token. `nats-server`'s own literal-subject check refuses a
//!   token that *is* `*` or `>` and accepts everything else, and this crate
//!   matches it, so `orders.*` is refused as a publish subject while
//!   `orders.*x` is not.
//! * **A `>` that is not the final token is refused rather than matched.**
//!   "and must be the final token" is a rule about the pattern, so
//!   `orders.>.created` is [`Error::InvalidSubject`] at the `subscribe` call
//!   rather than a pattern with a guessed meaning.
//! * **There is no reconnect loop.** "Client reconnection policy is a
//!   client-library policy, not a Core NATS wire guarantee" (§1), and B-165's
//!   acceptance does not ask for one. When the connection ends,
//!   [`Connection::closed`] reports why, every subscription ends with it —
//!   which is the protocol's behaviour, since core subscriptions have no
//!   stored session — and the material a policy needs is exposed: the failure,
//!   the retained `connect_urls` and [`Connection::lame_duck_notice`].
//!   Redialling and re-subscribing are the caller's, because only the caller
//!   knows whether its subscriptions are still wanted.
//! * **A message for a full subscription queue is dropped, not blocked on.**
//!   Core NATS is at-most-once and stores nothing for replay, and the server's
//!   own answer to a client that will not read is to buffer `max_pending`
//!   (64 MiB) and then disconnect it (§5, §11). Blocking the read loop would
//!   stall every other subscription on the connection and earn that
//!   disconnect anyway, so the copy is dropped with a `tracing::warn!`.
//! * **`INFO.max_payload` is enforced locally, before the wire.** The server
//!   would answer `-ERR 'Maximum Payload Violation'` and close; checking one
//!   comparison in the caller's own task costs nothing and keeps the
//!   connection. The same is done for `max_control_line`. For a headered
//!   publish the number checked is the *total*, because "headers count within
//!   the `HPUB` total size and therefore within the server's accepted message
//!   size" (§3).
//! * **A later `INFO` merges rather than replaces.** The reference does not
//!   say whether an asynchronous `INFO` is complete. Real ones are topology
//!   notices, so a field the notice does not mention is left alone — treating
//!   an absent `headers` as `false` would let a `connect_urls` update revoke
//!   header support. `connect_urls` itself is replaced, because the list is
//!   the topology as it now is. `ldm` only ever moves to `true`: a server does
//!   not leave Lame Duck Mode.
//! * **Retaining fewer `connect_urls` is a preference, not a refusal.** The
//!   codec *refuses* an array above its cap, which is right for a decoder: a
//!   JSON array announces no length, so the only place to stop is while
//!   reading it. But a caller who sets
//!   [`options::ConnectionOptions::max_connect_urls`] to 2 is saying how many
//!   it wants to keep, and a cluster that grew to 300 must not become a
//!   dropped connection over that. So the decode cap is never lowered below
//!   [`options::DEFAULT_MAX_CONNECT_URLS`] and the retention bound truncates
//!   afterwards. Raising the option above the default raises both.
//! * **A server that sends a client-to-server verb is a protocol error.**
//!   `CONNECT`, `PUB`, `HPUB`, `SUB` and `UNSUB` travel one way. So does a
//!   `sid`: it is "generated by the client", so a `MSG` carrying one this
//!   client could not have written is [`Error::Protocol`] rather than a
//!   message routed by guesswork.
//!
//! # Sources
//!
//! Every number and every quoted rule comes from `docs/research/nats.md`,
//! which cites the [client protocol
//! reference](https://docs.nats.io/reference/protocols/client) and the NATS
//! ADRs.

#![warn(missing_docs)]

pub mod connection;
pub mod error;
pub mod message;
pub mod options;
pub mod request;
pub mod subject;
pub mod subscription;
pub mod transport;

pub use connection::{Connection, RemoteInfo, State};
pub use error::{Error, Result};
pub use message::{Message, NO_RESPONDERS, OwnedHeaders};
pub use options::{ConnectionOptions, Credentials, NonceSignature, Signer};
pub use subscription::Subscription;
