//! Subscriptions: the client-chosen `sid`, the table it indexes, and
//! auto-unsubscribe.
//!
//! # The `sid` is the client's
//!
//! "`SUB <subject> [queue group] <sid>` — a unique alphanumeric subscription
//! ID, generated by the client." So the server never invents one and never
//! validates one beyond uniqueness on the connection: it is a routing token
//! the client hands out and the server quotes back in every `MSG`. This crate
//! allocates them as a monotonically increasing decimal `u64`, which is
//! unique for the life of a connection by construction and needs no lookup to
//! produce.
//!
//! A consequence worth stating: because the client picks them, **nothing but
//! the client can bound the table**. Each entry is a live channel, a subject
//! and a queue-group name, and the protocol says nothing about how many there
//! may be. [`ConnectionOptions::max_subscriptions`](crate::options::ConnectionOptions::max_subscriptions)
//! is that bound and it is ours.
//!
//! # `UNSUB` with a count is honoured twice
//!
//! `UNSUB <sid> [max_msgs]` is "a number of messages to wait for before
//! automatically unsubscribing", and the count is the *total* delivered on
//! that subscription, not a further N: a subscription that has had three and
//! is given `UNSUB sid 3` is done immediately. The server keeps that count
//! and so does [`Table`], for a reason that is not redundancy — the server
//! may well write the Nth `MSG` before it reads the `UNSUB`, and it certainly
//! writes any message already in flight. A client that only sent the count
//! would deliver messages past the one the caller asked to stop at.
//!
//! # A full queue drops the copy
//!
//! Each subscription has a bounded queue and a message that arrives for a
//! full one is dropped with a log line. The alternative — blocking the read
//! loop until the application collects — stalls every *other* subscription on
//! the connection and then earns a slow-consumer disconnect from the server
//! anyway, since the server buffers only `max_pending` (64 MiB) per client
//! before dropping it (`docs/research/nats.md` §5, §11). Core NATS is
//! at-most-once and stores nothing for replay, so a dropped copy is a loss
//! the delivery contract already allows; a stalled connection is not.

use std::collections::HashMap;

use tokio::sync::mpsc;

use crate::connection::Command;
use crate::message::Message;

/// One live subscription.
///
/// Dropping it unsubscribes: the handle is the subscription's lifetime, which
/// is what keeps the table from filling with interest nobody reads. The
/// `UNSUB` is best-effort on the drop path, because a `Drop` cannot await and
/// a connection that is already gone has no subscriptions to remove anyway.
#[derive(Debug)]
pub struct Subscription {
    sid: u64,
    subject: Vec<u8>,
    queue_group: Option<Vec<u8>>,
    messages: mpsc::Receiver<Message>,
    commands: mpsc::Sender<Command>,
    /// Set once an `UNSUB` has been asked for, so `Drop` does not send a
    /// second one.
    released: bool,
}

impl Subscription {
    pub(crate) fn new(
        sid: u64,
        subject: Vec<u8>,
        queue_group: Option<Vec<u8>>,
        messages: mpsc::Receiver<Message>,
        commands: mpsc::Sender<Command>,
    ) -> Self {
        Self {
            sid,
            subject,
            queue_group,
            messages,
            commands,
            released: false,
        }
    }

    /// The `sid` this client chose, which is what every `MSG` for this
    /// subscription carries.
    #[must_use]
    pub const fn sid(&self) -> u64 {
        self.sid
    }

    /// The subject or pattern this subscription asked for.
    #[must_use]
    pub fn subject(&self) -> &[u8] {
        &self.subject
    }

    /// The queue group, where this subscription joined one.
    #[must_use]
    pub fn queue_group(&self) -> Option<&[u8]> {
        self.queue_group.as_deref()
    }

    /// The next message, or `None` once the subscription has ended.
    ///
    /// Ends when the subscription is unsubscribed, when an auto-unsubscribe
    /// count is reached, or when the connection goes away — a Core NATS
    /// subscription has no existence apart from its connection.
    pub async fn next(&mut self) -> Option<Message> {
        self.messages.recv().await
    }

    /// The next message if one is already waiting.
    pub fn try_next(&mut self) -> Option<Message> {
        self.messages.try_recv().ok()
    }

    /// `UNSUB <sid>`: remove the subscription now.
    ///
    /// Messages the server had already written are still in the queue and
    /// still readable, because they were delivered before the `UNSUB` could
    /// be read. Dropping them would be pretending the `UNSUB` travelled back
    /// in time.
    pub async fn unsubscribe(&mut self) {
        self.request_unsubscribe(None).await;
    }

    /// `UNSUB <sid> <max_msgs>`: remove the subscription once it has received
    /// `max_msgs` messages in total.
    ///
    /// The count is the total on this subscription, as the server counts it,
    /// so a subscription that has already had that many ends at once.
    pub async fn unsubscribe_after(&mut self, max_msgs: u64) {
        self.request_unsubscribe(Some(max_msgs)).await;
    }

    async fn request_unsubscribe(&mut self, max_msgs: Option<u64>) {
        self.released = true;
        let _ = self
            .commands
            .send(Command::Unsubscribe {
                sid: self.sid,
                max_msgs,
            })
            .await;
    }
}

impl Drop for Subscription {
    fn drop(&mut self) {
        if self.released {
            return;
        }
        // Best-effort: a `Drop` cannot await, and a driver that is gone or
        // whose queue is full has either ended the subscription already or is
        // about to notice the closed channel on its next delivery.
        let _ = self.commands.try_send(Command::Unsubscribe {
            sid: self.sid,
            max_msgs: None,
        });
    }
}

/// What one delivery attempt did.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Delivered {
    /// Handed to the subscription. `exhausted` means an auto-unsubscribe
    /// count was reached and the entry is gone.
    Ok {
        /// Whether this was the last message the subscription asked for.
        exhausted: bool,
    },
    /// The subscription's queue was full and the copy was dropped.
    Dropped,
    /// Nobody is reading any more; the entry has been removed and an `UNSUB`
    /// is due.
    Gone,
    /// No subscription has that `sid`.
    Unknown,
}

/// One entry of the subscription table.
#[derive(Debug)]
struct Entry {
    subject: Vec<u8>,
    tx: mpsc::Sender<Message>,
    /// How many messages have been delivered on this `sid`, which is the
    /// number `UNSUB <sid> <max_msgs>` counts.
    delivered: u64,
    max_msgs: Option<u64>,
}

/// The subscription table, owned by the connection driver.
///
/// A `HashMap` keyed by `sid`, bounded by a number of ours. One owner: the
/// driver both dispatches into it and edits it, so there is no lock and no
/// window in which a `MSG` can arrive for a subscription that is half
/// inserted.
#[derive(Debug)]
pub(crate) struct Table {
    entries: HashMap<u64, Entry>,
    max: usize,
}

impl Table {
    pub(crate) fn new(max: usize) -> Self {
        Self {
            entries: HashMap::new(),
            max,
        }
    }

    /// Whether another subscription would fit.
    pub(crate) fn has_room(&self) -> bool {
        self.entries.len() < self.max
    }

    /// The bound, for the error that reports it.
    pub(crate) const fn max(&self) -> usize {
        self.max
    }

    pub(crate) fn insert(&mut self, sid: u64, subject: Vec<u8>, tx: mpsc::Sender<Message>) {
        self.entries.insert(
            sid,
            Entry {
                subject,
                tx,
                delivered: 0,
                max_msgs: None,
            },
        );
    }

    /// Removes a subscription. `true` where there was one to remove, which is
    /// what decides whether an `UNSUB` is worth writing.
    pub(crate) fn remove(&mut self, sid: u64) -> bool {
        self.entries.remove(&sid).is_some()
    }

    /// Records an auto-unsubscribe count.
    ///
    /// `false` where the subscription no longer exists. The entry is removed
    /// immediately where it has already received that many, because the count
    /// is a total and not a further N.
    pub(crate) fn set_max_msgs(&mut self, sid: u64, max_msgs: u64) -> bool {
        let Some(entry) = self.entries.get_mut(&sid) else {
            return false;
        };
        if entry.delivered >= max_msgs {
            self.entries.remove(&sid);
            return true;
        }
        entry.max_msgs = Some(max_msgs);
        true
    }

    /// Hands `message` to the subscription that asked for it.
    ///
    /// Never to any other: the `sid` is the routing key and a message whose
    /// `sid` is not in the table is dropped rather than matched against
    /// subjects. A client that re-matched subjects here would be second
    /// guessing the server's own routing, and would deliver a copy to a
    /// subscription whose `UNSUB` had already been processed.
    pub(crate) fn dispatch(&mut self, sid: u64, message: Message) -> Delivered {
        let Some(entry) = self.entries.get_mut(&sid) else {
            return Delivered::Unknown;
        };
        match entry.tx.try_send(message) {
            Ok(()) => {
                entry.delivered += 1;
                let exhausted = entry.max_msgs.is_some_and(|max| entry.delivered >= max);
                if exhausted {
                    self.entries.remove(&sid);
                }
                Delivered::Ok { exhausted }
            }
            Err(mpsc::error::TrySendError::Full(_)) => Delivered::Dropped,
            Err(mpsc::error::TrySendError::Closed(_)) => {
                self.entries.remove(&sid);
                Delivered::Gone
            }
        }
    }

    /// The subject a `sid` subscribed to, for a log line.
    pub(crate) fn subject(&self, sid: u64) -> Option<&[u8]> {
        self.entries.get(&sid).map(|entry| entry.subject.as_slice())
    }

    /// Closes every subscription, which is what the end of the connection
    /// does to them: "core subscriptions vanish with the connection and have
    /// no stored session".
    pub(crate) fn clear(&mut self) {
        self.entries.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn message(sid: u64) -> Message {
        Message {
            sid,
            subject: b"a.b".to_vec(),
            ..Message::default()
        }
    }

    /// A `MSG` goes to the subscription its `sid` names and to no other, even
    /// where both subscriptions match the same subject.
    #[test]
    fn a_message_reaches_only_the_sid_that_asked() {
        let mut table = Table::new(8);
        let (tx1, mut rx1) = mpsc::channel(4);
        let (tx2, mut rx2) = mpsc::channel(4);
        table.insert(1, b"a.b".to_vec(), tx1);
        table.insert(2, b"a.b".to_vec(), tx2);

        assert_eq!(
            table.dispatch(1, message(1)),
            Delivered::Ok { exhausted: false }
        );
        assert_eq!(rx1.try_recv().expect("delivered").sid, 1);
        assert!(
            rx2.try_recv().is_err(),
            "the other subscription matches the same subject and still gets nothing"
        );
        assert_eq!(table.dispatch(9, message(9)), Delivered::Unknown);
    }

    /// The count is a total, honoured locally: the fourth message on a
    /// subscription capped at three is not delivered even though the server
    /// wrote it.
    #[test]
    fn an_auto_unsubscribe_count_is_a_total_and_is_honoured_locally() {
        let mut table = Table::new(8);
        let (tx, mut rx) = mpsc::channel(8);
        table.insert(1, b"a.b".to_vec(), tx);

        assert_eq!(
            table.dispatch(1, message(1)),
            Delivered::Ok { exhausted: false }
        );
        assert!(table.set_max_msgs(1, 3), "the subscription is still there");
        assert_eq!(
            table.dispatch(1, message(1)),
            Delivered::Ok { exhausted: false }
        );
        assert_eq!(
            table.dispatch(1, message(1)),
            Delivered::Ok { exhausted: true },
            "the third is the last one asked for"
        );
        assert_eq!(
            table.dispatch(1, message(1)),
            Delivered::Unknown,
            "a fourth message the server had already written is not delivered"
        );
        let mut seen = 0;
        while rx.try_recv().is_ok() {
            seen += 1;
        }
        assert_eq!(seen, 3);
    }

    /// A count that is already satisfied ends the subscription at once, which
    /// is what "the total delivered" means.
    #[test]
    fn a_count_already_reached_ends_the_subscription_immediately() {
        let mut table = Table::new(8);
        let (tx, _rx) = mpsc::channel(8);
        table.insert(1, b"a.b".to_vec(), tx);
        table.dispatch(1, message(1));
        table.dispatch(1, message(1));
        assert!(table.set_max_msgs(1, 2));
        assert_eq!(table.dispatch(1, message(1)), Delivered::Unknown);
        assert!(
            !table.set_max_msgs(1, 5),
            "and there is nothing left to cap"
        );
    }

    /// A full queue costs one copy, not the connection.
    #[test]
    fn a_full_queue_drops_the_copy() {
        let mut table = Table::new(8);
        let (tx, mut rx) = mpsc::channel(1);
        table.insert(1, b"a.b".to_vec(), tx);
        assert_eq!(
            table.dispatch(1, message(1)),
            Delivered::Ok { exhausted: false }
        );
        assert_eq!(table.dispatch(1, message(1)), Delivered::Dropped);
        assert!(rx.try_recv().is_ok());
        assert!(
            rx.try_recv().is_err(),
            "the dropped copy is gone, and the subscription is still live"
        );
        assert_eq!(
            table.dispatch(1, message(1)),
            Delivered::Ok { exhausted: false },
            "a drop is not a removal"
        );
    }

    /// A reader that has gone away takes its entry with it, so the driver can
    /// write the one `UNSUB` that is due.
    #[test]
    fn a_dropped_reader_removes_its_entry_once() {
        let mut table = Table::new(8);
        let (tx, rx) = mpsc::channel(1);
        table.insert(1, b"a.b".to_vec(), tx);
        drop(rx);
        assert_eq!(table.dispatch(1, message(1)), Delivered::Gone);
        assert_eq!(
            table.dispatch(1, message(1)),
            Delivered::Unknown,
            "and only once"
        );
    }

    /// The bound is the client's, because the `sid` is.
    #[test]
    fn the_table_is_bounded() {
        let mut table = Table::new(2);
        for sid in 0..2 {
            let (tx, _rx) = mpsc::channel(1);
            assert!(table.has_room());
            table.insert(sid, b"a".to_vec(), tx);
        }
        assert!(!table.has_room());
        assert_eq!(table.max(), 2);
        assert!(table.remove(0));
        assert!(table.has_room());
        assert!(!table.remove(0), "removing twice is not two removals");
    }
}
